all:
	g++ -std=c++11 buttons.cpp -L/usr/X11/lib -lfltk_images -lz  -lfltk_gl -lGLU -lGL -lfltk -lXrender -lXcursor -lXfixes -lXext -lXinerama -lpthread -ldl -lm -lX11 -o buttons && ./buttons

go:
	./buttons