all:
	g++ -std=c++11 buttons.cpp -L/usr/X11/lib -lX11 -lfltk_images -lfltk_forms -lfltk_gl -lz  -lfltk_gl -lGLU -lGL -lfltk -lXrender -lXcursor -lXfixes -lXext -lXinerama -lpthread -ldl -lm  -o buttons && ./buttons

go:
	./buttons